export const names1 = [
  { name: "Vaughan" },
  { name: "Mireille" },
  { name: "Gerome" },
  { name: "Corinne" },
  { name: "Brig" },
  { name: "Yasmin" },
  { name: "Felicle" },
  { name: "Josephine" },
  { name: "Dionis" },
  { name: "Sheridan" },
  { name: "Staford" },
  { name: "Myrlene" },
  { name: "Tabbatha" },
  { name: "Olympia" },
  { name: "Gilberte" },
  { name: "Barty" },
  { name: "Dougie" },
  { name: "Evy" },
  { name: "Wit" },
  { name: "Ollie" },
  { name: "Malachi" },
  { name: "Leigh" },
  { name: "Dollie" },
  { name: "Lou" },
  { name: "Leonelle" },
  { name: "Inger" },
  { name: "Ruperto" },
  { name: "Sissie" },
  { name: "Rooney" },
  { name: "Lee" },
  { name: "Lemar" },
  { name: "Carole" },
  { name: "Pincus" },
  { name: "Jobina" },
  { name: "Carmela" },
  { name: "Durante" },
  { name: "Fred" },
  { name: "Gisella" },
  { name: "Iggie" },
  { name: "Ketti" },
  { name: "Pierce" },
  { name: "Thelma" },
  { name: "Farah" },
  { name: "Marven" },
  { name: "Jourdan" },
  { name: "Juliann" },
  { name: "Melissa" },
  { name: "Rubia" },
  { name: "Sax" },
  { name: "Janine" },
];

export const names2 = [
  { name: "Zoé" },
  { name: "Crééz" },
  { name: "Pénélope" },
  { name: "Célia" },
  { name: "Lyséa" },
  { name: "Liè" },
  { name: "Yè" },
  { name: "Gérald" },
  { name: "Marlène" },
  { name: "Mélinda" },
  { name: "Renée" },
  { name: "Léonore" },
  { name: "Adèle" },
  { name: "Maïlys" },
  { name: "Dorothée" },
  { name: "Eliès" },
  { name: "Léonie" },
  { name: "Clémence" },
  { name: "Ruì" },
  { name: "Frédérique" },
  { name: "Lén" },
  { name: "Cléopatre" },
  { name: "Faîtes" },
  { name: "Dafnée" },
  { name: "Valérie" },
  { name: "Lucrèce" },
  { name: "Marie-josée" },
  { name: "Loïc" },
  { name: "Maëlla" },
  { name: "Eugénie" },
  { name: "Céline" },
  { name: "Séréna" },
  { name: "Maëlann" },
  { name: "Måns" },
  { name: "Björn" },
  { name: "Dafnée" },
  { name: "Maéna" },
  { name: "Håkan" },
  { name: "Noémie" },
  { name: "Léa" },
  { name: "Jú" },
  { name: "Loïc" },
  { name: "Mélanie" },
  { name: "Valérie" },
  { name: "Clélia" },
  { name: "Wá" },
  { name: "Céline" },
  { name: "Illustrée" },
  { name: "Desirée" },
  { name: "Lóng" },
];

export const messages = [
  { name: "Orcinus orca" },
  { name: "Pan troglodytes" },
  { name: "Bubo virginianus" },
  { name: "Diceros bicornis" },
  { name: "Nasua nasua" },
  { name: "Lepus arcticus" },
  { name: "Pterocles gutturalis" },
  { name: "Crotalus cerastes" },
  { name: "Kobus vardonii vardoni" },
  { name: "Paraxerus cepapi" },
  { name: "Antechinus flavipes" },
  { name: "Zenaida galapagoensis" },
  { name: "Anser caerulescens" },
  { name: "Dusicyon thous" },
  { name: "Corallus hortulanus cooki" },
  { name: "Pycnonotus nigricans" },
  { name: "Bucephala clangula" },
  { name: "Eremophila alpestris" },
  { name: "Acridotheres tristis" },
  { name: "Felis silvestris lybica" },
  { name: "Genetta genetta" },
  { name: "Axis axis" },
  { name: "Odocoilenaus virginianus" },
  { name: "Zenaida galapagoensis" },
  { name: "Plegadis falcinellus" },
  { name: "Diomedea irrorata" },
  { name: "Loris tardigratus" },
  { name: "Bubalus arnee" },
  { name: "Capreolus capreolus" },
  { name: "Eudyptula minor" },
  { name: "Trichoglossus chlorolepidotus" },
  { name: "Vombatus ursinus" },
  { name: "unavailable" },
  { name: "Crax sp." },
  { name: "Tamiasciurus hudsonicus" },
  { name: "Laniaurius atrococcineus" },
  { name: "Thamnolaea cinnmomeiventris" },
  { name: "unavailable" },
  { name: "Oncorhynchus nerka" },
  { name: "Erinaceus frontalis" },
  { name: "Paradoxurus hermaphroditus" },
  { name: "Tadorna tadorna" },
  { name: "Isoodon obesulus" },
  { name: "Tragelaphus angasi" },
  { name: "Redunca redunca" },
  { name: "Potamochoerus porcus" },
  { name: "Dendrohyrax brucel" },
  { name: "Trichoglossus chlorolepidotus" },
  { name: "Ctenophorus ornatus" },
  { name: "Semnopithecus entellus" },
];
